# Generated by Django 2.2.5 on 2019-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
