# Generated by Django 2.2.5 on 2019-09-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20190916_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='project_link',
        ),
    ]
