# Generated by Django 2.2.5 on 2019-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_remove_team_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_name',
            field=models.CharField(default='Project_Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='deploy_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='git_url',
            field=models.URLField(),
        ),
    ]
