# Generated by Django 2.2.5 on 2020-10-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0013_auto_20201005_2330'),
    ]

    operations = [
    ]
