# Generated by Django 2.2.5 on 2020-10-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_auto_20201006_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
    ]
