# Generated by Django 2.2.5 on 2020-10-07 07:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_auto_20201007_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='team', to=settings.AUTH_USER_MODEL),
        ),
    ]
